package org.example.styler.helper.handler;

import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.example.antlr.JavaParser;
import org.example.parser.ExtendToken;
import org.example.parser.ParseTreeFactory;
import org.example.styler.helper.EquivalentStructure;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * @description
 * @author       Yingying Jiang
 * @create       2024/4/13 14:40
 */
public class OpOpAssignConvertHandler extends Handler{
	static private Map<Integer, ExtendToken> convertMap = new HashMap<>();
	static {
		convertMap.put(JavaParser.MUL, new ExtendToken(JavaParser.MUL_ASSIGN, "*="));
		convertMap.put(JavaParser.MUL_ASSIGN, new ExtendToken(JavaParser.MUL, "*"));
		convertMap.put(JavaParser.DIV, new ExtendToken(JavaParser.DIV_ASSIGN, "/="));
		convertMap.put(JavaParser.DIV_ASSIGN, new ExtendToken(JavaParser.DIV, "/"));
		convertMap.put(JavaParser.MOD, new ExtendToken(JavaParser.MOD_ASSIGN, "%="));
		convertMap.put(JavaParser.MOD_ASSIGN, new ExtendToken(JavaParser.MOD, "%"));

		convertMap.put(JavaParser.BITAND, new ExtendToken(JavaParser.AND_ASSIGN, "&="));
		convertMap.put(JavaParser.AND_ASSIGN, new ExtendToken(JavaParser.BITAND, "&"));
		convertMap.put(JavaParser.BITOR, new ExtendToken(JavaParser.OR_ASSIGN, "|="));
		convertMap.put(JavaParser.OR_ASSIGN, new ExtendToken(JavaParser.BITOR, "|"));

		convertMap.put(JavaParser.CARET, new ExtendToken(JavaParser.XOR_ASSIGN, "^="));
		convertMap.put(JavaParser.XOR_ASSIGN, new ExtendToken(JavaParser.CARET, "^"));

	}
	public OpOpAssignConvertHandler(String[][] argsList) {
		this.argsList = argsList;
	}

	/**
	 * args: [index1, index2, holderName1, holderName2]
	 * This has two meanings:
	 * from = index1, to = index2 -> convert from the ParseTree generated by holderName1 to holderName2
	 * from = index2, to = index1 -> convert from the ParseTree generated by holderName2 to holderName1
	 *
	 * @param structure
	 * @param from
	 * @param to
	 */
	@Override
	public void handle(EquivalentStructure structure, int from, int to) {
		for(String[] args : argsList) {
			int index1 = Integer.parseInt(args[0]);
			int index2 = Integer.parseInt(args[1]);
			String holderName1 = args[2];
			String holderName2 = args[3];
			String holderNameFrom = "", holderNameTo = "";
			if (index1 == from && index2 == to) {
				holderNameFrom = holderName1;
				holderNameTo = holderName2;
			} else if(index1 == to && index2 == from) {
				holderNameFrom = holderName2;
				holderNameTo = holderName1;
			} else {
				continue;
			}

			List<ParseTree> fromTrees = structure.getVNode(holderNameFrom).matchedNodes;
			List<ParseTree> toTrees = structure.getVNode(holderNameTo).matchedNodes = new ArrayList<>(fromTrees);
			for (int i = 0; i < fromTrees.size(); i++) {
				ParseTree tree = fromTrees.get(i);
				if(tree instanceof TerminalNode ter) {
					ExtendToken convertedToken = convertMap.get(ter.getSymbol().getType());
					if (convertedToken != null) {
						toTrees.set(i, ParseTreeFactory.createTerminalNode(convertedToken.clone()));
					}
				}
			}
		}
	}
}
