package org.example.web.model.entity;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class ProjectEntity {
    private final String projectKey;    // unique project key generated by backend
    /**
     * Generated and saved by client.
     * Vscode can use ExtensionContext.globalState to save and get the clientId.
     */
    private final String clientId;
    private final String localPath; // local abs path of the project

    @JsonCreator
    public ProjectEntity(
            @JsonProperty("projectKey") String projectKey,
            @JsonProperty("clientId") String clientId,
            @JsonProperty("localPath") String localPath
    ) {
        this.projectKey = projectKey;
        this.clientId = clientId;
        this.localPath = localPath;
    }
}
