package org.example.web.model.entity;

import lombok.Data;

@Data
public class ProjectEntity {
    private final String projectKey;    // unique project key generated by backend
    /**
     * Generated and saved by client.
     * Vscode can use ExtensionContext.globalState to save and get the clientId.
     */
    private final String clientId;
    private final String localPath; // local abs path of the project
}
