package org.example.styler.structure.handler;

import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.example.parser.java.antlr.JavaParser;
import org.example.parser.*;
import org.example.styler.structure.EquivalentStructure;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * @description
 * @author       Yingying Jiang
 * @create       2024/4/4 23:48
 */
public class CondReverserHandler extends Handler{
  // key: compare operator, value: reversing compare operator
  static Map<String, Token> compareOpMap;
  static Map<String, Token> logicalOpMap;

  static {
    compareOpMap = new HashMap<>();
    compareOpMap.put(">", new ExtendToken(JavaParser.LE, "<="));
    compareOpMap.put("<", new ExtendToken(JavaParser.GE, ">="));
    compareOpMap.put(">=", new ExtendToken(JavaParser.LT, "<"));
    compareOpMap.put("<=", new ExtendToken(JavaParser.GT, ">"));
    compareOpMap.put("==", new ExtendToken(JavaParser.NOTEQUAL, "!="));
    compareOpMap.put("!=", new ExtendToken(JavaParser.EQUAL, "=="));

    logicalOpMap = new HashMap<>();
    logicalOpMap.put("&&", new ExtendToken(JavaParser.OR, "||"));
    logicalOpMap.put("||", new ExtendToken(JavaParser.AND, "&&"));
  }

  public CondReverserHandler(String[][] argsList) {
    this.argsList = argsList;
  }

  /**
   * args:[index1, index2, holderName1, holderName2,...]
   * 1. from = index1, to = index2, reverse all ParseTree generated by holders from [holderName1,...]
   * 2. from = index2, to = index1, reverse all ParseTree generated by holders from [holderName1,...]
   * @param structure
   * @param from
   * @param to
   */
  @Override
  public void handle(EquivalentStructure structure, int from, int to) {
    for(String[] args : argsList) {
      int index1 = Integer.parseInt(args[0]), index2 = Integer.parseInt(args[1]);
      if(index1 == from && index2 == to || index1 == to && index2 == from) {
        for (int i = 2; i < args.length; i++) {
          String holderName = args[i];
          List<ParseTree> matchedTrees = structure.getVNode(holderName).matchedNodes;
          for (int j = 0; j < matchedTrees.size(); j++) {
            ParseTree t = matchedTrees.get(j);
            if (t instanceof JavaParser.ExpressionContext ctx) {
              matchedTrees.set(j, reverseCond(ctx));
            }
          }
        }
      }
    }
  }


  /**
   *
   * @param ctx
   * @return whether has unwrapped logical or expression
   */
  private ParseTree reverseCond(ExtendContext ctx) {
    ExtendToken op = getOp(ctx);
    Token reversedOp = compareOpMap.get(op.getText());
    if (reversedOp != null) {
      // reverse compare or logical operator
      op.setType(reversedOp.getType());
      op.setText(reversedOp.getText());
      return ctx;
    }

    reversedOp = logicalOpMap.get(op.getText());
    ExtendContext exp = ctx;
    if (reversedOp != null) {
      exp = ParseTreeFactory.getInstance().encapsulateExpByParen((ExtendContext) ctx);
    }
    // expression -> !expression or !expression -> expression
    ExtendContext notExp = ParseTreeFactory.getInstance().negateExpression(exp);
    return notExp;
  }

  private boolean wrappedByParen(ExtendContext ctx) {
    ExtendContext parent = (ExtendContext) ctx.getParent();
    return parent instanceof JavaParser.ExpressionContext && parent.start.getText().equals("(") && parent.stop.getText().equals(")");
  }

  /**
   * Find the comparison and logical operators.
   * @param ctx
   * @return
   */
  private ExtendToken getOp(ExtendContext ctx) {
    List<TerminalNode> ters = ctx.getAllTerminalsIf(v -> true);
    if (ters.isEmpty()) {
      return ExtendTokenFactory.DEFAULT.create(0, "");
    }
    return (ExtendToken) ters.get(0).getSymbol();
  }
}
