package org.example.styler.structure.handler;

import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.example.parser.common.*;
import org.example.parser.common.factory.ExtendTokenFactory;
import org.example.parser.java.antlr.JavaParser;
import org.example.styler.structure.EquivalentStructure;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * @description
 * @author       Yingying Jiang
 * @create       2024/4/4 23:48
 */
public class CondReverserHandler extends Handler{
  // key: compare operator, value: reversing compare operator
  static Map<String, String> compareOpMap ;
  static Map<String, String> logicalOpMap;

  static {
    compareOpMap = new HashMap<>();
    compareOpMap.put(">", "<=");
    compareOpMap.put("<", ">=");
    compareOpMap.put(">=", "<");
    compareOpMap.put("<=", ">=");
    compareOpMap.put("==", "!=");
    compareOpMap.put("!=", "==");

    logicalOpMap = new HashMap<>();
    logicalOpMap.put("&&", "||");
    logicalOpMap.put("||", "&&");
  }

  public CondReverserHandler(String[][] argsList) {
    this.argsList = argsList;
  }

  /**
   * args:[index1, index2, holderName1, holderName2,...]
   * 1. from = index1, to = index2, reverse all ParseTree generated by holders from [holderName1,...]
   * 2. from = index2, to = index1, reverse all ParseTree generated by holders from [holderName1,...]
   * @param structure
   * @param from
   * @param to
   */
  @Override
  public void handle(EquivalentStructure structure, int from, int to, MyParser parser) {
    for(String[] args : argsList) {
      int index1 = Integer.parseInt(args[0]), index2 = Integer.parseInt(args[1]);
      if(index1 == from && index2 == to || index1 == to && index2 == from) {
        for (int i = 2; i < args.length; i++) {
          String holderName = args[i];
          List<ParseTree> matchedTrees = structure.getVNode(holderName).matchedNodes;
          for (int j = 0; j < matchedTrees.size(); j++) {
            ParseTree t = matchedTrees.get(j);
            if (t instanceof JavaParser.ExpressionContext ctx) {
              matchedTrees.set(j, reverseCond(ctx, parser));
            }
          }
        }
      }
    }
  }


  /**
   *
   * @param ctx
   * @return whether has unwrapped logical or expression
   */
  private ParseTree reverseCond(ExtendContext ctx, MyParser parser) {
    ExtendToken op = (ExtendToken) getOp(ctx, parser);
    String reversedOp = compareOpMap.get(op.getText());
    if (reversedOp != null) {
      // reverse compare or logical operator
      op.setType(parser.getType(reversedOp));
      op.setText(reversedOp);
      return ctx;
    }

    reversedOp = logicalOpMap.get(op.getText());
    ExtendContext exp = ctx;
    if (reversedOp != null) {
      exp = ParseTreeFactory.getInstance().encapsulateExpWithParen(ctx, parser);
    }
    // expression -> !expression or !expression -> expression
    ExtendContext notExp = ParseTreeFactory.getInstance().negateExpression(exp, parser);
    return notExp;
  }

  private boolean wrappedByParen(ExtendContext ctx) {
    ExtendContext parent = (ExtendContext) ctx.getParent();
    return parent instanceof JavaParser.ExpressionContext && parent.start.getText().equals("(") && parent.stop.getText().equals(")");
  }

  /**
   * Find the comparison and logical operators.
   * @param ctx
   * @return
   */
  private Token getOp(ExtendContext ctx, MyParser parser) {
    List<TerminalNode> ters = ctx.getAllTerminalsIf(v -> true);
    if (ters.isEmpty()) {
      return parser.getTokenFactory().create(0, "");
    }
    return ters.get(0).getSymbol();
  }
}
