package org.example.styler.structure.handler;

import org.antlr.v4.runtime.TokenFactory;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.example.parser.common.ExtendToken;
import org.example.parser.common.ExtendTokenFactory;
import org.example.parser.common.MyParser;
import org.example.parser.common.ParseTreeFactory;
import org.example.parser.java.antlr.JavaParser;
import org.example.parser.ExtendToken;
import org.example.parser.ParseTreeFactory;
import org.example.styler.structure.EquivalentStructure;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * @description
 * @author       Yingying Jiang
 * @create       2024/4/13 14:40
 */
public class OpOpAssignConvertHandler extends Handler{
	static private Map<String, String> convertMap = new HashMap<>();
	static {
		convertMap.put("*", "*=");
		convertMap.put("*=", "*");
		convertMap.put("/", "/=");
		convertMap.put("/=", "/");
		convertMap.put("%", "%=");
		convertMap.put("%=", "%");

		convertMap.put("&", "&=");
		convertMap.put("&=", "&");
		convertMap.put("|", "|=");
		convertMap.put("|=", "|");
		convertMap.put("^", "^=");
		convertMap.put("^=", "^");

	}
	public OpOpAssignConvertHandler(String[][] argsList) {
		this.argsList = argsList;
	}

	/**
	 * args: [index1, index2, holderName1, holderName2]
	 * This has two meanings:
	 * from = index1, to = index2 -> convert from the ParseTree generated by holderName1 to holderName2
	 * from = index2, to = index1 -> convert from the ParseTree generated by holderName2 to holderName1
	 *
	 * @param structure
	 * @param from
	 * @param to
	 */
	@Override
	public void handle(EquivalentStructure structure, int from, int to, MyParser parser) {
		for(String[] args : argsList) {
			int index1 = Integer.parseInt(args[0]);
			int index2 = Integer.parseInt(args[1]);
			String holderName1 = args[2];
			String holderName2 = args[3];
			String holderNameFrom = "", holderNameTo = "";
			if (index1 == from && index2 == to) {
				holderNameFrom = holderName1;
				holderNameTo = holderName2;
			} else if(index1 == to && index2 == from) {
				holderNameFrom = holderName2;
				holderNameTo = holderName1;
			} else {
				continue;
			}

			List<ParseTree> fromTrees = structure.getVNode(holderNameFrom).matchedNodes;
			List<ParseTree> toTrees = structure.getVNode(holderNameTo).matchedNodes = new ArrayList<>(fromTrees);
			for (int i = 0; i < fromTrees.size(); i++) {
				ParseTree tree = fromTrees.get(i);
				if(tree instanceof TerminalNode ter) {
					String convertedOp = convertMap.get(ter.getSymbol().getText());
					if (convertedOp != null) {
						toTrees.set(i, ParseTreeFactory.createTerminalNode(ExtendTokenFactory.DEFAULT.create(parser.getType(convertedOp), convertedOp)));
					}
				}
			}
		}
	}
}
