package org.example.styler.structure;


import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.TerminalNode;
import org.example.parser.common.ExtendContext;
import org.example.parser.common.MyParser;
import org.example.parser.common.ParseTreeFactory;
import org.example.parser.java.MyJavaParser;
import org.example.myException.CompilationException;
import org.example.styler.structure.checker.Checker;
import org.example.styler.structure.handler.Handler;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*
 * @description
 * @author       Yingying Jiang
 * @create       2024/4/2 23:40
 */
public class EquivalentStructure {

	int id;
	String category;
	int[] rules;
	List<VirtualTree> vTrees = new ArrayList<>();
	VirtualNodeContainer vNodeContainer = null;
	Map<Integer, List<Integer>> bannedTransfer;

	// key: tree generated by holder
	Map<ParseTree, VirtualNode> treeVNodeMap = new HashMap<>();
	List<Checker> checkers = null;
	List<Handler> handlers = null;

	public EquivalentStructure(int id, String category, int[] rules, List<Checker> checkers,
	                           List<Handler> handlers, Map<Integer, List<Integer>> bannedTransfer) {
		this.category = category;
		this.id = id;
		this.rules = rules;
		this.checkers = checkers;
		this.handlers = handlers;
		this.bannedTransfer = bannedTransfer;
	}

	public void setHandlers(List<Handler> handlers) {
		this.handlers = handlers;
	}

	public void setCheckers(List<Checker> checkers) {
		this.checkers = checkers;
	}

	void compile(String[] codes, String[] holders) {
		try {
			vNodeContainer = new VirtualNodeContainer(holders);
			int rule = rules[0];
			for (int i = 0; i < codes.length; i++) {
				boolean flag = codes[i].startsWith("$^");
				String code = replaceHolder(codes[i]);
				if (id == 26) {
					System.out.println("");
				}
				MyJavaParser parser = new MyJavaParser(code);
				if (i < rules.length) {
					rule = rules[i];
				}
				int priority = getPriority(code);
				vTrees.add(new VirtualTree(parser.parse(rule, flag), priority));
				uniqueVNodes(vNodeContainer);
			}
		} catch (CompilationException e) {
			System.err.println("The equivalent structure with id:" + id + " has a compilation error:" + e.getMessage());
			System.err.println("Please ensure adjacent tokens in configured codes are seperated by space!");
		}
	}

	public int getPriority(int index) {
		return vTrees.get(index).priority;
	}

	// get priority for the code.
	private int getPriority(String code) {
		String[] strs = code.split(" ");
		int priority = strs.length;
		for(String str : strs) {
			if(str.isEmpty() || str.matches("\\$.\\d*[+*?]")){
				priority -= 1;
			}
		}
		return priority;
	}


	public Integer getId() {
		return id;
	}

	public String getCategory() {
		return category;
	}

	public VirtualNode getVNode(String holderName) {
		return vNodeContainer.getVNodeByHolderName(holderName);
	}

	public int match(ParseTree t, MyParser parser) {
		// Virtual tree that has a greater priority is matched first.
		Map<VirtualTree, Integer> vtMap = new TreeMap<>();
		for (int i = 0; i < vTrees.size(); i++) {
			VirtualTree vtree = vTrees.get(i);
			vtMap.put(vtree, i);
		}

		ExtendContext tParent = (ExtendContext) t.getParent();
		int startIndex = tParent.children.indexOf(t);

		for (Map.Entry<VirtualTree, Integer> entry : vtMap.entrySet()) {
			VirtualTree vtree = entry.getKey();
			int index = entry.getValue();
			cleanState();

			int vi = 0, ti = startIndex;
			for (; vi < vtree.trees.size() && ti < tParent.getChildCount(); ++vi,++ti) {
				ParseTree vt = vtree.trees.get(vi);
				ParseTree t1 = tParent.getChild(ti);
				if (t1 instanceof TerminalNode || vt instanceof TerminalNode) {
					break;
				}
				int rule1 = ((ExtendContext) t1).getRuleIndex();
				int rule2 = ((ExtendContext) vt).getRuleIndex();
				if (rule1 != rule2) {
					break;
				}
//				System.out.println(vt.toStringTree(new JavaParser(null)));
//				System.out.println(t1.toStringTree(new JavaParser(null)));
				if (!isMatched(vt, t1, vtree.context, parser)) {
					break;
				}
			}
			if(vi == vtree.trees.size() && vtree.context.isMatched(parser) && check(index))  {
				return index;
			}
		}
		cleanState();
		return -1;
	}

	private boolean check(int index) {
		if (checkers == null) {
			return true;
		}
		for (Checker checker : checkers) {
			if (!checker.check(this, index)) {
				return false;
			}
		}
		return true;
	}

	public ParseTree convert(int from, int to, ParseTree oldTree, MyParser parser) {
		if(bannedTransfer != null && bannedTransfer.get(from) != null && bannedTransfer.get(from).contains(to)) {
			return null;
		}
		if (handlers != null) {
			for (Handler handler : handlers) {
				handler.handle(this, from, to, parser);
			}
		}

		VirtualTree vtree = vTrees.get(to);
		int fromSize = vTrees.get(from).trees.size();
		int toSize = vtree.trees.size();
		List<ParseTree> newTrees = new ArrayList<>(1);
		for(ParseTree t : vtree.trees) {

			// System.out.println(t.toStringTree(new JavaParser(null)));
			newTrees.add(createTree(t, vtree.context));
		}

		// Update old trees to new trees.
		ExtendContext parent = (ExtendContext) oldTree.getParent();
		int startIndex = parent.children.indexOf(oldTree);
		parent.replaceChildren(startIndex, startIndex + fromSize, newTrees);
		cleanState();
		return newTrees.isEmpty() ? null : newTrees.get(0);
	}

	/**
	 * @apiNote Before calling this method, ensure there's a virtual tree matching with a real tree.
	 * @param t t doesn't have an associated virtual node and t is a ExtendContext instance.
	 * @return
	 */
	private ParseTree createTree(ParseTree t, Context context) {
		ExtendContext ctx = (ExtendContext) t;

		// Create children
		List<ParseTree> children = new ArrayList<>();
		for (ParseTree child : ctx.children) {
			children.addAll(context.getTreesBefore(child));
			VirtualNode vNode = treeVNodeMap.get(child);
			if (vNode != null) {
				children.addAll(vNode.matchedNodes);
			} else if(child instanceof TerminalNode) {
				children.add(ParseTreeFactory.getInstance().copyFrom(child, null, false));
			} else {
				children.add(createTree(child, context));
			}
		}

		// Create parent
		ParseTree newTree = ParseTreeFactory.getInstance().copyFrom(t, children, false);

		// ParseTreeFactory.getInstance().replaceTree(t.getParent(), newTree, t);
		return newTree;
	}

	private void cleanState() {
		for(VirtualNode vNode : treeVNodeMap.values()) {
			vNode.cleanState();
		}
		for(VirtualTree vt : vTrees) {
			vt.context.cleanState();
		}
	}

	private boolean ruleMatches(ExtendContext ctx1, ExtendContext ctx2) {
		return ctx1.getRuleIndex() == ctx2.getRuleIndex();
	}

	/**
	 * @apiNote Both vt and t are common tree nodes, in other words, they are not associated with a virtual node.
	 * @param vt
	 * @param t
	 * @return
	 */
	private boolean isMatched(ParseTree vt, ParseTree t, Context context, MyParser parser) {
		if (vt instanceof TerminalNode && t instanceof TerminalNode) {
			return vt.getText().equals(t.getText());
		}
		if (vt instanceof ExtendContext && t instanceof ExtendContext) {
			ExtendContext vtCtx = (ExtendContext) vt;
			ExtendContext ctx = (ExtendContext) t;
			// Match rule.
			if(!ruleMatches(vtCtx, ctx)) {
				return false;
			}

			// Match children
			int vi = 0, i = 0;
			while (vi < vt.getChildCount() && i < t.getChildCount()) {
				ParseTree cChild = vt.getChild(vi), tChild = t.getChild(i);
				VirtualNode virtualNode = treeVNodeMap.get(cChild);
				boolean matched = false;
				if (virtualNode != null) {
					matched = virtualNode.matches(tChild, parser);
					if (matched) {
						virtualNode.addMatchedTree(tChild);
					}
				} else {
					matched = isMatched(cChild, tChild, context, parser);
				}

				if (matched) {
					++vi;
					++i;
				} else {
					if(!context.addContext(cChild, tChild)) {
						return false;
					}
					++i;
				}
			}
			return vi == vt.getChildCount() && i == t.getChildCount();
		}
		return false;
	}


	/**
	 * @apiNote After the method is called, parent filed of ParseTree is invalid.
	 */
	private void uniqueVNodes(VirtualNodeContainer virtualNodeContainer) {
		for (VirtualTree vt : vTrees) {
			for(ParseTree t : vt.trees) {
				doUnique(t, vt.context);
			}
		}
	}

	// param t is a real tree.
	private void doUnique(ParseTree parent, Context context) {
		if (!(parent instanceof ExtendContext)) {
			return;
		}
		List<ParseTree> children = ((ExtendContext) parent).children;
		for (int i = 0; i < children.size(); i++) {
			ParseTree child = children.get(i);
			VirtualNode vNode = vNodeContainer.getVNodeByText(child.getText());
			if (vNode != null) {
				if(!vNode.repetition.isEmpty()) { // Handle the virtual node whose holder name is end up with '*','+' or '?'.
					checkRepeatableVNode(children, i);
					children.remove(i);
					ParseTree next = children.get(i);
					context.addContext(next, vNode);
					--i;
				} else {
					if (vNode.isEmpty()) {
						treeVNodeMap.put(child, vNode);
						vNode.t = child;
					} else {
						children.set(i, vNode.t);
					}
				}
			} else {
				doUnique(child, context);
			}
		}
	}

	private void checkRepeatableVNode (List<ParseTree> children, int i) {
		if (i == children.size() - 1) {
			throw new CompilationException("wrong structure: holder name ending with '*','+' or '?' can't occur at the end.");
		}
		ParseTree next = children.get(i + 1);
		VirtualNode vNode = vNodeContainer.getVNodeByText(next.getText());
		if(vNode != null && !vNode.repetition.isEmpty()) {
			throw new CompilationException("wrong structure: holder name ending with '*','+' or '?' can't occur continuously.");
		}
	}

	private String replaceHolder(String code) {
		// Holder name with a longer prefix should be replaced first.
		List<String> holderNames = vNodeContainer.getHolderNames().stream().sorted(Comparator.comparing(s -> -s.length())).toList();
		boolean flag = code.startsWith("$^");
		String[] strs = code.split(" ");
		StringBuilder retCode = new StringBuilder();
		for(String str : strs) {
			for(String holderName : holderNames) {
				str = str.replace(holderName, vNodeContainer.getValue(holderName));
			}
			retCode.append(str);
			retCode.append(" ");
		}
		if (flag) {
			return "{" + retCode.toString().replace("$^", "") + "}";
		}
		return retCode.toString();

	}

	static class VirtualNodeMatcher {
		private static Map<Class, VirtualNodeMatcher> instances = new HashMap<>(0);
		private Map<String, Set<Integer>> matchRules = new HashMap<>();
		private Map<String, Set<Integer>> matchTokens = new HashMap<>();

		private VirtualNodeMatcher(MyParser parser) {
			init(parser);
		}

		public static VirtualNodeMatcher getInstance(MyParser parser) {
			VirtualNodeMatcher ret = instances.get(parser.getClass());
			if (ret == null) {
				ret = new VirtualNodeMatcher(parser);
				instances.put(parser.getClass(), ret);
			}
			return ret;
		}


		public boolean isMatched(String type, ParseTree tree, MyParser parser) {
			init(parser);
			if(tree instanceof TerminalNode) {
				if(tree.getText().equals(";") && type.equals("$S")) {
					return true;
				}
				return matchTokens.get(type) != null && matchTokens.get(type).contains(((TerminalNode) tree).getSymbol().getText());
			} else {
				int rule = ((ExtendContext) tree).getRuleIndex();
				Set<Integer> rules = matchRules.get(type);
				return rules != null && rules.contains(rule);
			}
		}

		private void init(MyParser parser) {
			matchRules.put("$I", Set.of(parser.getRuleIdentifier(), parser.getRuleExpression()));
			matchRules.put("$C", Set.of(parser.getRuleExpression()));
			matchRules.put("$E", Set.of(parser.getRuleExpression()));
			matchRules.put("$S", parser.getAllStmts());
			matchRules.put("$T", Set.of(parser.getRuleTypeType()));
			matchRules.put("$M", Set.of(parser.getRuleModifierList()));

			matchRules.put("$S(ifStmt)", Set.of(parser.getRuleIfStmt()));
			matchRules.put("$S(ifElseStmt)", Set.of(parser.getRuleIfElseStmt()));

			matchTokens.put("$I", Set.of(parser.getIdentifier()));
			matchTokens.put("$HOMO_BOP", parser.getHomoOps());
			matchTokens.put("$HOMO_BOP_ASSIGN", parser.getOpAssign());
			matchTokens.put("$LITERAL", parser.getLiterals());
		}
	}

	public static class VirtualNode {

		public ParseTree t = null;
		public List<ParseTree> matchedNodes = new ArrayList<>(0);
		public String type;
		public String repetition;


		public VirtualNode(String type, String repetition) {
			this.type = type;
			this.repetition = repetition;
		}

		public void addMatchedTree(ParseTree tChild) {
			matchedNodes.add(tChild);
		}

		public void cleanState() {
			matchedNodes.clear();
		}

		public boolean isEmpty() {
			return t == null;
		}
		
		public boolean matches(ParseTree t1, MyParser parser) {
			return VirtualNodeMatcher.getInstance(parser).isMatched(type, t1, parser);
		}

		public boolean checkState(MyParser parser) {
			// Check tree type correct.
			for (ParseTree tree : matchedNodes) {
				if (!VirtualNodeMatcher.getInstance(parser).isMatched(type, tree, parser)) {
					return false;
				}
			}

			// Check size correct.
			int sizeBefore = matchedNodes.size();
			return repetition.isEmpty() && sizeBefore == 0 ||
					repetition.equals("*") ||
					repetition.equals("+") && sizeBefore >= 1 ||
					repetition.equals("?") && sizeBefore <= 1;
		}


		@Override
		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || getClass() != o.getClass()) return false;
			VirtualNode that = (VirtualNode) o;
			return Objects.equals(t, that.t);
		}

		@Override
		public int hashCode() {
			return Objects.hash(t);
		}
	}

	static class VirtualTree implements Comparable {

		List<ParseTree> trees = new ArrayList<>(1);
		Context context = new Context();
		int priority = 0;

		public VirtualTree(List<ParseTree> trees, int priority) {
			this.trees = trees;
			this.priority = priority;
		}

		@Override
		public int compareTo(Object o) {
			VirtualTree vtree = (VirtualTree) o;
			if(this.equals(o)) {
				return 0;
			}
			return priority > vtree.priority ? -1 : 1;
		}

	}

	static class Context {
		Map<ParseTree, VirtualNode> contexts = new HashMap<>();

		public void addContext(ParseTree t, VirtualNode virtualNode) {
			contexts.put(t, virtualNode);
		}

		public boolean addContext(ParseTree t, ParseTree treeBefore) {
			// Only tree with previous  r"\\$.\\d*[*+?] can successfully add.
			if (contexts.get(t) == null) {
				return false;
			}
			contexts.get(t).matchedNodes.add(treeBefore);
			return true;
		}

		public void cleanState() {
			for(VirtualNode vNode : contexts.values()) {
				vNode.matchedNodes.clear();
			}
		}

		public boolean isMatched(MyParser parser) {
			for (VirtualNode vNode : contexts.values()) {
				if(!vNode.checkState(parser)) {
					return false;
				}
			}
			return true;
		}

		public List<ParseTree> getTreesBefore(ParseTree t) {
			VirtualNode vNode = contexts.get(t);
			return vNode != null ? vNode.matchedNodes : new ArrayList<>(0);
		}
	}

	/**
	 * $I: identifier
	 * $C： conditional expression
	 * $E: expression
	 * $S: any statement
	 * $M: modifier list
	 * $T: typeType
	 * $V: variableDeclaratorId
	 * $S(type): statement with type.
	 * $^: for example: "$^ if($C) { return true;} return false;", this structure will be considered as a ifStmt.
	 * When we get a ifStmt, this statement will be tried to match the structure. If matched, we'll see the next
	 * statement,that's returnStmt.
	 * $-: binary operator that doesn't satisfy the commutative law
	 * $-=: compound assign operator of non-commutative operator(such as: -=, /=, %=)
	 * $+: binary operator that satisfies the commutative law
	 * $+=: compound assign operator of non-commutative operator(such as:+=,*=)
	 */
	static class VirtualNodeContainer {

		// key: holder value, value:holder names
		Map<String, List<String>> valueNameMap = new HashMap<>();
		Map<String, Holder> holders = new HashMap<>();
		// Ensure each pattern has three groups. If regular1 is a prefix of regular2 then regular1 should be put after regular2.
		static Pattern[] holderPatterns = {
				Pattern.compile("(\\$[ICSEMVT^])(\\d*)([*+?]?)"),
				Pattern.compile("(\\$S\\([a-zA-Z]+\\))(\\d*)([*+?]?)"),
				Pattern.compile("(\\$HOMO_BOP_ASSIGN)(\\d*)()"),
				Pattern.compile("(\\$HOMO_BOP)(\\d*)()"),
				Pattern.compile("(\\$LITERAL)(\\d*)()")
		};
		private static final Map<String, String> holderMap = new HashMap<>(){{
			put("$I", "I");put("$C", "C");put("$E", "E");put("$V", "V");put("$T", "T");put("$M", "");
			put("$S(ifStmt)", "if(true){}");put("$S(ifElseStmt)", "if(true){}else{}");put("$S", "S#id=S#id;");
			put("$HOMO_BOP", "+");put("$HOMO_BOP_ASSIGN", "+=");put("$LITERAL", "1");
			put("", "");
		}};
		static int TYPE_GROUP = 1;
		static int DIGITAL_GROUP = 2;
		static int REPETITION_GROUP = 3;

		public VirtualNodeContainer(String[] holderNames) {
			for (int i = 0; i < holderNames.length; i++) {
				String holderName = holderNames[i];
				Holder holderObj = createHolder(holderName, i);
				holderObj.vNode = new VirtualNode(holderObj.type, holderObj.repetition);
				holders.put(holderName, holderObj);
			}
		}

		public Holder getHolder(String holderName) {
			return holders.get(holderName);
		}

		public String getValue(String holderName) {
			Holder holder = holders.get(holderName);
			if (holder != null) {
				return holder.holderValue;
			}
			return null;
		}

		public Set<String> getHolderNames() {
			return holders.keySet();
		}

		/**
		 * @apiNote This method can't handle the case where different holder names has the same holder value.
		 * @param holderValue
		 * @return
		 */
		public String getHolderName(String holderValue) {
			for(Holder holder : holders.values()) {
				if(holder.holderValue.equals(holderValue)) {
					return holder.holderName;
				}
			}
			return null;
		}

		/**
		 * @apiNote This method can handle the case where different holder names has the same holder value.
		 * But there may be some bugs.
		 * @param holderValue
		 * @return
		 */
		public String getHolderName(String holderValue, boolean modifyState) {
			List<String> holderNames = valueNameMap.get(holderValue);
			if (holderNames != null) {
				if (modifyState) {
					String first = holderNames.get(0);
					holderNames.remove(0);
					holderNames.add(first);
				}
				return holderNames.get(0);
			}
			return null;
		}

		/**
		 * @apiNote This method can't handle the case where different holder names has the same holder value.
		 * @return
		 */
		public VirtualNode getVNodeByText(String text) {
			String holderName = getHolderName(text);
			Holder holder = holders.get(holderName);
			if (holder != null) {
				return holder.vNode;
			}
			return null;
		}

		public VirtualNode getVNodeByHolderName(String holderName) {
			return holders.get(holderName) == null ? null : holders.get(holderName).vNode;
		}


		/**
		 * @apiNote This method can handle the case where different holder names has the same holder value.
		 * But there may be some bugs.
		 * @param text
		 * @return
		 */
		public VirtualNode getVNodeByText(String text, boolean modifyState) {
			String holderName = getHolderName(text, modifyState);
			Holder holder = holders.get(holderName);
			if (holder != null) {
				return holder.vNode;
			}
			return null;
		}



		private Holder createHolder(String holderName, int index) {
			String type = "", digitalId = "", repetition = "";
			for(Pattern holderPattern : holderPatterns) {
				Matcher matcher = holderPattern.matcher(holderName);
				if (matcher.matches() && matcher.group(TYPE_GROUP).length() > type.length()) {
					type = matcher.group(TYPE_GROUP);
					digitalId = matcher.group(DIGITAL_GROUP);
					repetition = matcher.group(REPETITION_GROUP);
				}
			}
			String holderValue = holderMap.getOrDefault(type, "").replace("#id", digitalId);
			valueNameMap.computeIfAbsent(holderValue, v -> new ArrayList<>());
			valueNameMap.get(holderValue).add(holderName);
			return new Holder(holderName, holderValue, index, repetition, type);
		}

		public static class Holder {
			String holderName;
			String holderValue;
			int index;
			String repetition;
			String type;
			VirtualNode vNode = null;

			public Holder(String holderName, String holderValue, int index, String repetition, String type) {
				this.holderName = holderName;
				this.holderValue = holderValue;
				this.index = index;
				this.repetition = repetition;
				this.type = type;
			}
		}
	}
}
