spring:
  application:
    name: transformer

general:
  #  When a value's proportion >= `minDominantRatio`, it is considered dominant, and the style is assigned this value.
  minDominantRatio: 0.7

stylers:


lang:
  all:
    java:
      parser: org.example.lang.java.MyJavaParser
      treeNodeFactory: org.example.lang.java.JavaTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      nodeSearcherFactory: org.example.lang.java.JavaNodeSearcherFactory
      placeholderParser: org.example.lang.java.JavaPlaceholderParser
      equivalencesConfig: "/equivalences.xml"

    cpp:
      parser: org.example.lang.cpp.MyCppParser
      treeNodeFactory: org.example.lang.cpp.CppTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      equivalencesConfig: "/cpp-equivalences.xml"

    python:
      parser: org.example.lang.python.MyPythonParser
      treeNodeFactory: org.example.lang.python.PythonTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      equivalencesConfig: "/python-equivalences.xml"

llm:
  apikey: "your-api-key"
  url: "https://api.example.com"
  model: "gpt-4.1"
  identifier-length-limit: 64
  temperature: 0.6
  max-new-tokens: 1024