spring:
  application:
    name: transformer
  main:
    banner-mode: off

project:
  #  When a value's proportion >= `minDominantRatio`, it is considered dominant, and the style is assigned this value.
  minDominantRatio: 0.7
  styleOutputDir: "./style-data/style-profiles"
  projectsFile: "./style-data/projects.json"
  styleProfilesFile: "./style-data/style-profiles.json"
  threadPool:
    corePoolSize: 3
    maxPoolSize: 10
    keepAliveSeconds: 60
    queueCapacity: 50

stylers:


lang:
  all:
    java:
      parser: org.example.lang.java.MyJavaParser
      treeNodeFactory: org.example.lang.java.JavaTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      nodeSearcherFactory: org.example.lang.java.JavaNodeSearcherFactory
      placeholderParser: org.example.lang.java.JavaPlaceholderParser
      symbolResolver: org.example.lang.java.symbol.JavaResolver
      typeResolver: org.example.lang.base.symbol.TypeResolverImpl
      astNodeSearcher: org.example.lang.java.JavaASTNodeSearcher
      equivalencesConfig: "/equivalences.xml"


    cpp:
      parser: org.example.lang.cpp.MyCppParser
      treeNodeFactory: org.example.lang.cpp.CppTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      placeholderParser: org.example.lang.cpp.CppPlaceholderParser
      symbolResolver: org.example.lang.java.symbol.JavaResolver
      typeResolver: org.example.lang.base.symbol.TypeResolverImpl
      equivalencesConfig: "/cpp_equivalences.xml"

    python:
      parser: org.example.lang.python.MyPythonParser
      treeNodeFactory: org.example.lang.python.PythonTreeNodeFactory
      astRewriter: org.example.lang.base.ASTRewriterBase
      equivalencesConfig: "/python-equivalences.xml"

llm:
  apikey: "your-api-key"
  url: "https://api.example.com"
  model: "gpt-4.1"
  identifier-length-limit: 64
  temperature: 0.6
  max-new-tokens: 1024
